apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: omkarnanda/bookstore
          # ports:
          #   - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore  # Match the label used in your Deployment
  ports:
    - protocol: TCP
      port: 9000  # The port your application is listening on in the container
      targetPort: 9000  # The port your application is listening on in the pod
      nodePort: 31280
  type: LoadBalancer  # Use LoadBalancer type to expose externally          

