apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60