apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: omkarnanda/user
          # ports:
          #   - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user  # Match the label used in your Deployment
  ports:
    - protocol: TCP
      port: 9000  # The port your application is listening on in the container
      targetPort: 9000  # The port your application is listening on in the pod
      nodePort: 32550
  type: LoadBalancer  # Use LoadBalancer type to expose externally